# Generated by Django 4.2.7 on 2023-11-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qrcode',
            fields=[
                ('S_No', models.IntegerField(primary_key=True, serialize=False)),
                ('QR_Id', models.CharField(max_length=50)),
                ('Registration_Status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'qrcode',
            },
        ),
    ]
